"use client";
import { useEffect,useRef,useState,type FormEvent } from 'react';
import { X,ArrowRight,RefreshCw,Paperclip,Download,CalendarClock,CheckCircle2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Checkbox } from '@/components/ui/checkbox';
import { Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription } from '@/components/ui/dialog';
import { Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription } from '@/components/ui/sheet';
import { Skeleton } from '@/components/ui/skeleton';
import { toast } from 'sonner';
import { Choice,Badge,Priority } from './controles';
import { altaSchema,gestionSchema,etapas,tiposPorEtapa,tipos,estados,prioridades,resultados,puedeCambiar,alerta,fechaLocal,fechaVisible,type Alta,type Incidencia,type Miembro,type Gestion,type Evento,type Adjunto,type Estado,type Etapa } from '@/lib/logistica';
export const message=(e:unknown)=>e instanceof Error?e.message:'No se pudo completar la operación';
export async function api<T>(path='',init?:RequestInit):Promise<T>{
  const r=await fetch('/api/incidencias'+path,{cache:'no-store',...init});const data=await r.json().catch(()=>({error:'No se pudo leer la respuesta del servidor'})) as T&{error?:string};if(!r.ok)throw new Error(data.error||'No se pudo completar la operación');return data;
}
export function nuevaAlta(userId:string):Alta{return {id:crypto.randomUUID(),operacion:'',expedicion:'',cliente:'',telefono:'',origen:'',destino:'',mensajeria:'MRW',empresaTipo:'TRANSPORTISTA',agente:'',etapa:'ESPANA',tipo:'NO_RECIBIDO_MADRID',prioridad:'MEDIA',fechaEnvio:'',fechaIncidencia:fechaLocal(),responsableId:userId,proximaAccion:'',fechaLimite:fechaLocal(),observaciones:'',bultos:''};}
export function AltaDialog({open,onOpenChange,draft,setDraft,equipo,onSaved}:{open:boolean;onOpenChange:(v:boolean)=>void;draft:Alta|null;setDraft:React.Dispatch<React.SetStateAction<Alta|null>>;equipo:Miembro[];onSaved:(r:Incidencia)=>void}){
  const [busy,setBusy]=useState(false);const [error,setError]=useState('');
  async function submit(e:FormEvent){e.preventDefault();if(!draft||busy)return;const parsed=altaSchema.safeParse(draft);if(!parsed.success){setError(parsed.error.issues[0].message);return;}setBusy(true);setError('');try{const r=await api<{incidencia:Incidencia}>('',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(parsed.data)});onSaved(r.incidencia);onOpenChange(false);setDraft(null);toast.success('Incidencia registrada');}catch(e){setError(message(e));}finally{setBusy(false);}}
  function field(key:keyof Alta,label:string,required=false,type='text',max=150){return <label className="field" htmlFor={'alta-'+key}>{label}{required?' *':''}<Input id={'alta-'+key} name={key} type={type} required={required} maxLength={max} value={draft?.[key]??''} onChange={e=>setDraft(d=>d?{...d,[key]:e.target.value}:d)}/></label>;}
  function select(key:keyof Alta,label:string,options:Record<string,string>){return <label className="field" htmlFor={'alta-'+key}>{label} *<Choice id={'alta-'+key} label={label} value={draft?.[key]??''} options={options} onChange={value=>setDraft(d=>d?{...d,[key]:value}:d)}/></label>;}
  return <Dialog open={open} onOpenChange={v=>!busy&&onOpenChange(v)}><DialogContent className="incident-dialog" showCloseButton={false}><DialogHeader><DialogTitle>Nueva incidencia</DialogTitle><DialogDescription>Datos del envío y primera acción de seguimiento. * Campos obligatorios.</DialogDescription></DialogHeader><Button className="close-panel" variant="ghost" size="icon" disabled={busy} onClick={()=>onOpenChange(false)} aria-label="Cerrar formulario"><X size={18}/></Button><form onSubmit={submit}><fieldset disabled={busy}><h3 className="form-section">01 · Envío y cliente</h3><div className="form-grid">{field('operacion','Guía / referencia',true,'text',60)}{field('expedicion','Expedición / bulto',false,'text',60)}{field('cliente','Cliente',true)}{field('telefono','Teléfono',false,'tel',40)}{field('origen','Origen',true,'text',100)}{field('destino','Destino',true,'text',100)}{field('fechaEnvio','Fecha de recogida',false,'date')}{field('fechaIncidencia','Fecha de incidencia',false,'date')}</div>
      <h3 className="form-section">02 · Qué ha ocurrido</h3><div className="form-grid"><label className="field" htmlFor="alta-etapa">Etapa del envío *<Choice id="alta-etapa" label="Etapa del envío" value={draft?.etapa??'ESPANA'} options={etapas} onChange={value=>setDraft(d=>d?{...d,etapa:value as Etapa,tipo:Object.keys(tiposPorEtapa[value as Etapa])[0]}:d)}/></label>{select('tipo','Tipo de incidencia',tiposPorEtapa[draft?.etapa??'ESPANA'])}{select('empresaTipo','Parte implicada',{TRANSPORTISTA:'Transportista',CORRESPONSAL:'Corresponsal',OTRO:'Otro / aduanas'})}{field('mensajeria','Empresa implicada',true,'text',100)}{select('prioridad','Prioridad',prioridades)}{field('agente','Agencia / origen interno',false,'text',100)}{field('bultos','Bultos / paquetes',false,'text',60)}<label className="field full" htmlFor="alta-observaciones">Descripción / observaciones<Textarea id="alta-observaciones" maxLength={3000} value={draft?.observaciones??''} onChange={e=>setDraft(d=>d?{...d,observaciones:e.target.value}:d)} placeholder="Describe lo que comunica el cliente o la empresa…"/></label></div>
      <div className="followup-form"><h3><CalendarClock size={17}/> Primer seguimiento</h3><div className="form-grid">{select('responsableId','Responsable',Object.fromEntries(equipo.map(m=>[m.id,m.nombre])))}{field('fechaLimite','Fecha límite',true,'date')}<div className="full">{field('proximaAccion','Próxima acción',true,'text',500)}</div></div><p>Podrás adjuntar fotos y documentos desde el detalle del expediente.</p></div></fieldset>{error&&<p className="error-box" role="alert">{error}</p>}<div className="form-footer"><span>Se registrará quién crea el caso y cuándo.</span><Button type="submit" disabled={busy}>{busy?'Guardando…':'Registrar incidencia'}<ArrowRight size={16}/></Button></div></form></DialogContent></Dialog>;
}
type Detail={incidencia:Incidencia;eventos:Evento[];adjuntos:Adjunto[]};
function nuevaGestion(r:Incidencia):Gestion{return {version:r.version,estado:r.estado==='CERRADA'?'EN_GESTION':r.estado,motivo:'',responsableId:r.responsableId,proximaAccion:r.proximaAccion,fechaLimite:r.fechaLimite,resultado:(r.resultado||'') as Gestion['resultado'],confirmacionCliente:false};}
export function Detalle({initial,equipo,onClose,onSaved,now}:{initial:Incidencia;equipo:Miembro[];onClose:()=>void;onSaved:(r:Incidencia)=>void;now:Date}){
  const [record,setRecord]=useState(initial);const [events,setEvents]=useState<Evento[]>([]);const [files,setFiles]=useState<Adjunto[]>([]);
  const [form,setForm]=useState<Gestion>(nuevaGestion(initial));const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [file,setFile]=useState<File|null>(null);const fileInput=useRef<HTMLInputElement>(null);
  useEffect(()=>{let active=true;api<Detail>('?id='+initial.id).then(d=>{if(active){setRecord(d.incidencia);setForm(nuevaGestion(d.incidencia));setEvents(d.eventos);setFiles(d.adjuntos);}}).catch(e=>active&&setError(message(e))).finally(()=>active&&setLoading(false));return()=>{active=false;};},[initial.id]);
  async function reload(preserve=false){setLoading(true);setError('');try{const d=await api<Detail>('?id='+record.id);setRecord(d.incidencia);setEvents(d.eventos);setFiles(d.adjuntos);setForm(f=>preserve?{...f,version:d.incidencia.version}:{...nuevaGestion(d.incidencia),motivo:f.motivo});onSaved(d.incidencia);}catch(e){setError(message(e));}finally{setLoading(false);}}
  async function submit(e:FormEvent){e.preventDefault();if(busy||loading)return;const parsed=gestionSchema.safeParse(form);if(!parsed.success){setError(parsed.error.issues[0].message);return;}setBusy(true);setError('');try{const d=await api<{incidencia:Incidencia}>('?id='+record.id,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(parsed.data)});setRecord(d.incidencia);setForm(nuevaGestion(d.incidencia));onSaved(d.incidencia);toast.success('Gestión guardada');const history=await api<Detail>('?id='+record.id);setEvents(history.eventos);}catch(e){setError(message(e));}finally{setBusy(false);}}
  async function upload(e:FormEvent){e.preventDefault();if(!file||busy)return;setBusy(true);setError('');try{const data=new FormData();data.set('archivo',file);data.set('id',record.id);data.set('version',String(record.version));const res=await fetch('/api/adjuntos',{method:'POST',body:data});const result=await res.json() as {error?:string};if(!res.ok)throw new Error(result.error||'No se pudo adjuntar');setFile(null);if(fileInput.current)fileInput.current.value='';await reload(true);toast.success('Documento adjuntado');}catch(e){setError(message(e));}finally{setBusy(false);}}
  const warning=alerta(record,now);const cierre=form.estado==='CERRADA';const solucion=['SOLUCIONADA','CERRADA'].includes(form.estado);
  return <Sheet open onOpenChange={v=>!v&&!busy&&onClose()}><SheetContent className="incident-sheet" showCloseButton={false}><SheetHeader><p className="eyebrow">EXPEDIENTE</p><SheetTitle>{record.referencia}</SheetTitle><SheetDescription>{record.operacion} · {record.cliente}</SheetDescription></SheetHeader><Button className="close-panel" size="icon" variant="ghost" disabled={busy} onClick={onClose} aria-label="Cerrar detalle"><X size={18}/></Button><div className="detail-body"><div className="detail-top"><div className="badges"><Priority value={record.prioridad}/><Badge estado={record.estado}/></div><Button size="sm" variant="ghost" disabled={busy||loading} onClick={()=>reload()}><RefreshCw size={14}/> Actualizar detalle</Button></div>
    {warning.nivel>0&&<div className={'followup-note level-'+warning.nivel}><CalendarClock size={17}/><div><b>{warning.texto}</b><p>{record.proximaAccion||'Registra una próxima acción'} · {fechaVisible(record.fechaLimite)}</p></div></div>}
    <dl className="detail-grid">{[['Guía / referencia',record.operacion],['Teléfono',record.telefono],['Origen',record.origen],['Destino',record.destino],['Empresa implicada',record.mensajeria],['Etapa',etapas[record.etapa]],['Tipo de incidencia',tipos[record.tipo]??record.tipo],['Responsable',record.responsable],['Fecha de recogida',fechaVisible(record.fechaEnvio)],['Fecha de incidencia',fechaVisible(record.fechaIncidencia)],['Expedición / bulto',record.expedicion],['Creada por',record.creadoNombre]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value||'Sin indicar'}</dd></div>)}</dl>
    {record.observaciones&&<div className="observations"><h3>Descripción del caso</h3><p>{record.observaciones}</p></div>}
    {record.resultado&&<p className="solution-note"><CheckCircle2 size={17}/> Resultado: {resultados[record.resultado as keyof typeof resultados]??record.resultado}{record.confirmacionCliente?' · Confirmado con el cliente':''}</p>}
    <section className="change-section"><h3>{record.estado==='CERRADA'?'Reabrir expediente':'Registrar gestión'}</h3><p>Qué has hecho y cuál será el siguiente paso.</p>{loading?<Skeleton className="h-24"/>:<form onSubmit={submit}><fieldset disabled={busy}><div className="form-grid"><label className="field" htmlFor="gestion-estado">Estado<Choice id="gestion-estado" label="Estado de la gestión" value={form.estado} options={Object.fromEntries(Object.entries(estados).filter(([key])=>puedeCambiar(record.estado,key as Estado)))} onChange={estado=>setForm(f=>({...f,estado:estado as Estado}))}/></label><label className="field" htmlFor="gestion-responsable">Responsable *<Choice id="gestion-responsable" label="Responsable de seguimiento" value={form.responsableId} options={Object.fromEntries(equipo.map(m=>[m.id,m.nombre]))} onChange={responsableId=>setForm(f=>({...f,responsableId}))}/></label><label className="field full" htmlFor="gestion-motivo">Gestión realizada *<Textarea id="gestion-motivo" required maxLength={3000} value={form.motivo} onChange={e=>setForm(f=>({...f,motivo:e.target.value}))} placeholder="Respuesta recibida, reclamación realizada o solución propuesta…"/></label>
    {!cierre&&<><label className="field full" htmlFor="gestion-accion">Próxima acción *<Input id="gestion-accion" required maxLength={500} value={form.proximaAccion} onChange={e=>setForm(f=>({...f,proximaAccion:e.target.value}))}/></label><label className="field" htmlFor="gestion-fecha">Fecha límite *<Input id="gestion-fecha" type="date" required value={form.fechaLimite} onChange={e=>setForm(f=>({...f,fechaLimite:e.target.value}))}/></label></>}
    {solucion&&<label className="field" htmlFor="gestion-resultado">Resultado *<Choice id="gestion-resultado" label="Resultado de la solución" value={form.resultado} options={resultados} onChange={resultado=>setForm(f=>({...f,resultado:resultado as Gestion['resultado']}))}/></label>}
    {cierre&&<label className="confirm-label full" htmlFor="confirmacion-cliente"><Checkbox id="confirmacion-cliente" checked={form.confirmacionCliente} onCheckedChange={checked=>setForm(f=>({...f,confirmacionCliente:checked===true}))}/> He comprobado con el cliente la solución y dejo constancia en la gestión.</label>}</div></fieldset><Button type="submit" disabled={busy}>{busy?'Guardando…':'Guardar gestión'}</Button></form>}</section>
    {error&&<p className="error-box" role="alert">{error}</p>}
    <section className="documents"><h3><Paperclip size={17}/> Documentos y pruebas</h3><p>PDF, JPG, PNG o WebP · máximo 10 MB por archivo.</p>{files.map(f=><a className="document-link" href={'/api/adjuntos?id='+f.id} key={f.id}><Paperclip size={15}/><span>{f.nombre}<small>{Math.ceil(f.tamano/1024)} KB · {f.actor_nombre}</small></span><Download size={15}/></a>)}<form onSubmit={upload}><Input ref={fileInput} aria-label="Seleccionar documento" type="file" accept=".pdf,.jpg,.jpeg,.png,.webp" disabled={busy||loading} onChange={e=>setFile(e.target.files?.[0]??null)}/><Button type="submit" variant="outline" disabled={!file||busy||loading}>Adjuntar</Button></form></section>
    <section className="history"><h3>Historial del expediente</h3>{events.map(e=><article key={e.id}><div className="history-dot"/><div><h4>{e.accion==='CREAR'?'Incidencia registrada':e.accion==='ADJUNTO'?'Documento añadido':e.anterior?.estado!==e.nuevo.estado?`${estados[e.anterior!.estado]} → ${estados[e.nuevo.estado]}`:'Gestión registrada'}</h4><p>{e.motivo}</p>{e.accion!=='ADJUNTO'&&e.nuevo.proximaAccion&&<p className="event-next">Siguiente: {e.nuevo.proximaAccion} · {fechaVisible(e.nuevo.fechaLimite)}</p>}<small>{e.actor_nombre} · {fechaVisible(e.fecha)} · {new Date(e.fecha).toLocaleTimeString('es-ES',{timeZone:'Europe/Madrid',hour:'2-digit',minute:'2-digit'})}</small></div></article>)}</section>
    </div></SheetContent></Sheet>;
}
