"use client";
import { AlertTriangle,Clock3,Search,CheckCircle2,Package,ArrowRight,UserRound,ChartNoAxesCombined,Truck,Bell,Plus,History } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Skeleton } from '@/components/ui/skeleton';
import { alerta,fechaLocal,fechaVisible,tipos,type Incidencia } from '@/lib/logistica';
import { indicadores,agrupar,misTareas,atencion } from '@/lib/indicadores';
export type Actividad={id:string;incidencia_id:string;actor_nombre:string;accion:string;motivo:string;fecha:string};
const colors=['#c9233c','#ec847a','#9c3047','#f2b75b','#7c889b','#88b7a0'];
export function Estadisticas({rows,loading,now,onFilter}:{rows:Incidencia[];loading:boolean;now:Date;onFilter:(v:string)=>void}){
  const k=indicadores(rows,now);
  const cards=[{key:'URGENTES',title:'Urgentes / vencidas',caption:'Requieren atención',icon:AlertTriangle,value:k.urgentes},{key:'RESPUESTA',title:'Pendientes de respuesta',caption:'Tercero o cliente',icon:Clock3,value:k.respuesta},{key:'EN_GESTION',title:'En gestión',caption:'Casos en investigación',icon:Search,value:k.gestion},{key:'RESUELTAS_HOY',title:'Resueltas hoy',caption:'Solución registrada hoy',icon:CheckCircle2,value:k.resueltasHoy},{key:'ABIERTAS',title:'Total abiertas',caption:'Casos sin solucionar',icon:Package,value:k.abiertas}];
  return <div className="kpi-grid">{cards.map(({key,title,caption,icon:Icon,value},i)=><button className={'kpi kpi-'+i} key={key} onClick={()=>onFilter(key)}><Icon size={30} strokeWidth={1.7}/><div><strong>{loading?'—':value}</strong><span>{title}</span><small>{caption}</small></div></button>)}</div>;
}
export function Graficos({rows,now}:{rows:Incidencia[];now:Date}){
  const month=fechaLocal(now).slice(0,7);const data=rows.filter(r=>fechaLocal(r.creadoEn).startsWith(month));
  const types=agrupar(data,'tipo');const top=types.slice(0,5);if(types.length>5)top.push({nombre:'Otros',total:types.slice(5).reduce((sum,r)=>sum+r.total,0)});
  const carriers=agrupar(data,'mensajeria');
  return <><section className="panel chart-panel"><h2><ChartNoAxesCombined size={18}/> Incidencias por tipo <small>Este mes</small></h2><div className="donut-layout"><div className="donut"><svg viewBox="0 0 120 120" role="img" aria-label={data.length?`${data.length} incidencias este mes`:'Sin incidencias este mes'}><circle cx="60" cy="60" r="44" fill="none" stroke="#eef0f3" strokeWidth="17"/>{top.map((item,i)=>{const fraction=item.total/data.length*276.46;const start=top.slice(0,i).reduce((sum,r)=>sum+r.total,0)/data.length*276.46;return <circle key={item.nombre} cx="60" cy="60" r="44" fill="none" stroke={colors[i]} strokeWidth="17" strokeDasharray={`${fraction} ${276.46-fraction}`} strokeDashoffset={-start} transform="rotate(-90 60 60)"/>;})}</svg><div><strong>{data.length}</strong><span>incidencias</span></div></div><ul className="legend">{top.length?top.map((r,i)=><li key={r.nombre}><i style={{background:colors[i]}}/><span>{tipos[r.nombre]??r.nombre}<b>{r.total} <small>({Math.round(r.total/data.length*100)} %)</small></b></span></li>):<li className="muted">Los tipos aparecerán al registrar incidencias.</li>}</ul></div></section><section className="panel chart-panel"><h2><Truck size={18}/> Empresas implicadas <small>Este mes</small></h2><div className="bar-list">{carriers.length?carriers.slice(0,6).map(r=><div key={r.nombre}><span title={r.nombre}>{r.nombre}</span><div><i style={{width:`${r.total/(carriers[0]?.total||1)*100}%`}}/></div><b>{r.total}</b></div>):<p className="chart-empty">Todavía no hay incidencias este mes.</p>}</div></section></>;
}
export function TareasCard({rows,userId,nombre,now,onView}:{rows:Incidencia[];userId:string;nombre:string;now:Date;onView:()=>void}){
  const mine=misTareas(rows,userId,now);const vencidas=mine.filter(r=>alerta(r,now).vencida);
  const otras=mine.filter(r=>!alerta(r,now).vencida);
  const cliente=otras.filter(r=>r.estado==='ESPERANDO_CLIENTE');const terceros=otras.filter(r=>r.estado!=='ESPERANDO_CLIENTE');
  const counts=[vencidas.length,terceros.filter(r=>r.empresaTipo==='TRANSPORTISTA').length,terceros.filter(r=>r.empresaTipo==='CORRESPONSAL').length,cliente.length];
  const hora=Number(new Intl.DateTimeFormat('es-ES',{timeZone:'Europe/Madrid',hour:'numeric',hourCycle:'h23'}).format(now));
  return <section className="panel tasks-card"><h2><UserRound size={19}/> Mi trabajo de hoy <button className="text-link" onClick={onView}>Ver tareas <ArrowRight size={14}/></button></h2><h3>{hora<12?'Buenos días':hora<20?'Buenas tardes':'Buenas noches'}, {nombre.split(' ')[0]}</h3><p>{mine.length?`Tienes ${mine.length} gestiones que revisar.`:'No tienes gestiones pendientes para hoy.'}</p><div className="task-counts">{['Vencidas','Transportistas','Corresponsales','Contactar cliente'].map((label,i)=><button onClick={onView} className={'task-mini mini-'+i} key={label}><b>{counts[i]}</b><span>{label}</span></button>)}</div></section>;
}
export function PieDashboard({rows,updates,now,onOpen,onView,onNew}:{rows:Incidencia[];updates:Actividad[];now:Date;onOpen:(r:Incidencia)=>void;onView:()=>void;onNew:()=>void}){
  const alerts=atencion(rows,now).slice(0,4);
  return <div className="dashboard-bottom"><section className="panel activity-panel"><h2><History size={18}/> Últimas actualizaciones</h2>{updates.length?updates.slice(0,4).map(e=>{const r=rows.find(r=>r.id===e.incidencia_id);return <button key={e.id} className="activity-row" onClick={()=>r&&onOpen(r)}><time>{new Date(e.fecha).toLocaleTimeString('es-ES',{timeZone:'Europe/Madrid',hour:'2-digit',minute:'2-digit'})}</time><span><b>{e.actor_nombre}</b> · {e.motivo}<small>{r?.referencia} · {fechaVisible(e.fecha)}</small></span></button>;}):<p className="quiet-empty">Aquí aparecerán las gestiones del equipo.</p>}</section><section className="panel activity-panel"><h2><Bell size={18}/> Recordatorios y alertas <button className="text-link" onClick={onView}>Ver todos <ArrowRight size={14}/></button></h2>{alerts.length?alerts.map(r=><button className="activity-row" key={r.id} onClick={()=>onOpen(r)}><AlertTriangle size={15} className={alerta(r,now).nivel===3?'red':'amber'}/><span>{alerta(r,now).texto}<small>{r.referencia} · {r.proximaAccion||'Asigna la próxima acción'}</small></span></button>):<p className="quiet-empty">No hay seguimientos que requieran atención.</p>}</section><div className="quick-actions"><Button onClick={onNew}><Plus size={25}/><span>Nueva incidencia<small>Registrar un nuevo caso</small></span></Button><p>España <ArrowRight size={13}/> Madrid <ArrowRight size={13}/> Latinoamérica</p></div></div>;
}
export function CargaDashboard(){return <div className="dashboard-middle">{[1,2,3].map(n=><Skeleton key={n} className="h-52"/>)}</div>;}
